name: Build APK with Buildozer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build APK using Kivy Docker image
      run: |
        docker run --privileged -v ${{ github.workspace }}:/home/user/host_project -w /home/user/host_project kivy/buildozer:2024.08.14 buildozer android debug
        
    - name: Show APK path
      run: ls -l bin || echo "No APK generated"

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: musicplayer-apk
        path: |
          bin/*.apk
