name: Build APK with Buildozer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build APK using Buildozer Docker image
      uses: ArtemSBulgakov/buildozer-action@v1
      id: buildozer
      with:
        command: buildozer android debug
        # Optionally, you can set the cache key for faster builds
        # cache_key: ${{ runner.os }}-buildozer-v1
        
    - name: Show APK path
      run: ls -l bin || echo "No APK generated"

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: musicplayer-apk
        path: |
          bin/*.apk
