name: Build APK with Buildozer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          python3-pip \
          build-essential \
          git \
          zip \
          unzip \
          openjdk-11-jdk \
          libncurses5 \
          libstdc++6 \
          zlib1g-dev \
          libffi-dev \
          libssl-dev \
          libsqlite3-dev \
          libjpeg-dev \
          clang \
          ccache \
          curl

    - name: Install Buildozer and Cython
      run: |
        python3 -m pip install --upgrade pip
        pip install buildozer cython

    - name: Add ~/.local/bin to PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Set up Android SDK tools
      run: |
        mkdir -p ~/.android && touch ~/.android/repositories.cfg
        buildozer android update
        yes | buildozer android clean
        yes | sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"
        yes | sdkmanager --licenses

    - name: Build APK
      run: buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: musicplayer-apk
        path: bin/*.apk
