name: Build APK with Buildozer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          python3-pip \
          build-essential \
          git \
          zip \
          unzip \
          openjdk-11-jdk \
          libncurses5 \
          libstdc++6 \
          zlib1g-dev \
          libffi-dev \
          libssl-dev \
          libsqlite3-dev \
          libjpeg-dev \
          clang \
          ccache

        python3 -m pip install --upgrade pip
        pip install --user buildozer cython

    - name: Add ~/.local/bin to PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install Android SDK Build Tools
      run: |
        yes | sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"
        yes | sdkmanager --licenses

    - name: Initialize Buildozer (first run will generate buildozer.spec)
      run: buildozer init || true

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: musicplayer-apk
        path: bin/*.apk
