name: Build APK with Buildozer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          python3-pip \
          build-essential \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          libncurses6 \
          libstdc++6 \
          zlib1g-dev \
          libffi-dev \
          libssl-dev \
          libsqlite3-dev \
          libjpeg-dev \
          clang \
          ccache \
          curl \
          libncurses-dev # Required for some older ndk versions

    - name: Install Buildozer and Cython
      run: |
        python3 -m pip install --upgrade pip
        pip install --user buildozer cython

    - name: Add ~/.local/bin to PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      
    - name: Install Android SDK Command-Line Tools
      run: |
        mkdir -p "$HOME/android-sdk"
        curl -o "$HOME/commandlinetools.zip" https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        unzip -q -d "$HOME/android-sdk/cmdline-tools" "$HOME/commandlinetools.zip" # Extract directly into 'cmdline-tools'
        rm "$HOME/commandlinetools.zip"
        mv "$HOME/android-sdk/cmdline-tools/cmdline-tools" "$HOME/android-sdk/cmdline-tools/latest" # Move the extracted folder into 'latest'
        mkdir -p "$HOME/.android"
        touch "$HOME/.android/repositories.cfg"

    - name: Set environment variables
      run: |
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "ANDROIDNDK=$HOME/android-ndk-r25b" >> $GITHUB_ENV
        echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

    - name: Accept Android SDK licenses
      run: |
        yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses
    
    - name: Install SDK components
      run: |
        sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;25.1.8937393"
        
    - name: Link NDK manually
      run: |
        ln -s "$ANDROID_SDK_ROOT/ndk/25.1.8937393" "$ANDROIDNDK"          
          
    - name: Initialize Buildozer (optional, only if buildozer.spec is missing)
      run: buildozer init || true

    - name: Build APK
      run: buildozer android debug

    - name: Show APK path
      run: ls -l bin || echo "No APK generated"

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: musicplayer-apk
        path: |
          bin/*.apk
